version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand({ping:1}).ok' || exit 1"]
      interval: 30s
      timeout: 90s
      retries: 20
      start_period: 300s
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g
    networks:
      - default
volumes:
  mongo_data:
networks:
  default:
    driver: bridge
