global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
  - job_name: 'audit-service'
    static_configs:
      - targets: ['audit-service:8081']
  - job_name: 'tax-engine'
    static_configs:
      - targets: ['tax-engine:8082']
